import type { SubscriptionPlanDto } from './types';

export const mockSubscriptionPlans: SubscriptionPlanDto[] = [
  {
    id: 'plan-lady',
    code: 'LADY',
    name: 'LADY',
    description: 'Fallback only for isolated component tests.',
    monthlyPriceRub: 2490,
    periodDays: 30,
    discountPercent: 20,
    certificateDiscountPercent: 10,
    includedCredits: 1,
    includedDescription: '1 любой массаж 60 мин или 1 процедура ухода за лицом',
    freezeCountPerYear: 1,
    freezeDays: 30,
    familyMembersLimit: 1,
  },
  {
    id: 'plan-lady-super',
    code: 'LADY_SUPER',
    name: 'LADY SUPER',
    description: 'Fallback only for isolated component tests.',
    monthlyPriceRub: 4490,
    periodDays: 30,
    discountPercent: 30,
    certificateDiscountPercent: 20,
    includedCredits: 2,
    includedDescription: '2 услуги на выбор: массажи 60 мин или уход за лицом',
    freezeCountPerYear: 2,
    freezeDays: 30,
    familyMembersLimit: 1,
  },
  {
    id: 'plan-mister',
    code: 'MISTER',
    name: 'MISTER',
    description: 'Fallback only for isolated component tests.',
    monthlyPriceRub: 2990,
    periodDays: 30,
    discountPercent: 20,
    certificateDiscountPercent: 10,
    includedCredits: 1,
    includedDescription: '1 любой массаж для мужчин 60 мин',
    freezeCountPerYear: 1,
    freezeDays: 30,
    familyMembersLimit: 1,
  },
  {
    id: 'plan-mister-super',
    code: 'MISTER_SUPER',
    name: 'MISTER SUPER',
    description: 'Fallback only for isolated component tests.',
    monthlyPriceRub: 5390,
    periodDays: 30,
    discountPercent: 30,
    certificateDiscountPercent: 20,
    includedCredits: 2,
    includedDescription: '2 любых массажа для мужчин по 60 мин',
    freezeCountPerYear: 2,
    freezeDays: 30,
    familyMembersLimit: 1,
  },
  {
    id: 'plan-family',
    code: 'FAMILY',
    name: 'FAMILY',
    description: 'Fallback only for isolated component tests.',
    monthlyPriceRub: 4700,
    periodDays: 30,
    discountPercent: 20,
    certificateDiscountPercent: 10,
    includedCredits: 2,
    includedDescription: '2 участника: по 1 услуге каждому',
    freezeCountPerYear: 1,
    freezeDays: 30,
    familyMembersLimit: 2,
  },
  {
    id: 'plan-family-super',
    code: 'FAMILY_SUPER',
    name: 'FAMILY SUPER',
    description: 'Fallback only for isolated component tests.',
    monthlyPriceRub: 8400,
    periodDays: 30,
    discountPercent: 30,
    certificateDiscountPercent: 20,
    includedCredits: 4,
    includedDescription: '4 участника: по 1 услуге каждому',
    freezeCountPerYear: 2,
    freezeDays: 30,
    familyMembersLimit: 4,
  },
];
