export {
  AdminMasterDetailsPage,
  AdminDashboardPage,
  AdminSchedulePage,
  AdminMastersPage,
  AdminStudiosPage,
  SuperAdminDashboardPage,
  SuperAdminMastersPage,
  SuperAdminSchedulePage,
  SuperAdminServiceDetailsPage,
  SuperAdminServicesPage,
} from './ui/AdminCrmPages';

export {
  AdminAppointmentsPage,
  AdminCertificatesPage,
  AdminClientsPage,
  AdminPaymentsPage,
  AdminRequestsPage,
  AdminServicesPage,
  AdminStudioProfilePage,
  AdminSubscriptionsPage,
  SuperAdminAnalyticsPage,
  SuperAdminAppointmentsPage,
  SuperAdminAuditLogPage,
  SuperAdminCertificatesPage,
  SuperAdminClientsPage,
  SuperAdminPaymentsPage,
  SuperAdminRequestsPage,
  SuperAdminSettingsPage,
  SuperAdminSubscriptionsPage,
  SuperAdminTariffsPage,
  SuperAdminUsersPageExtended as SuperAdminUsersPage,
} from './ui/AdminResourcePages';
